CREATE TABLE categories(id SERIAL PRIMARY KEY,name VARCHAR(100));
CREATE TABLE products(id SERIAL PRIMARY KEY,name VARCHAR(100),price NUMERIC,category_id INT REFERENCES categories(id));
CREATE TABLE admins(id SERIAL PRIMARY KEY,email VARCHAR(100),password VARCHAR(255));
CREATE TABLE orders(id SERIAL PRIMARY KEY,status VARCHAR(30),created_at TIMESTAMP DEFAULT NOW());
